filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"
    json.keys_under_root: true
    json.add_error_key: true
    multiline:
      pattern: '^{'
      negate: true
      match: after

output.logstash:
  hosts: ["elk:5044"]

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
