version: '3'
services:
  main-api:
    build:
      context: .
      dockerfile: ThreatIntelligencePlatform.Api/Dockerfile
    ports:
      - "8888:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  users-db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tip_users
  
  iocs-db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tip_iocs