services:
  frontend:
    container_name: tip-frontend
    build:
      context: .
      dockerfile: threat-intelligence-platform-frontend/Dockerfile
    ports:
      - "9999:5173"
    networks:
      - tip-network
  
  main-api:
    container_name: tip-main-api
    build:
      context: .
      dockerfile: ThreatIntelligencePlatform.API/Dockerfile
    ports:
      - "8888:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnectionString=Host=users-db;Port=5432;Database=tip_users;Username=admin;Password=admin
    depends_on:
      - users-db
      - database-microservice
    networks:
      - tip-network
  
  database-microservice:
    container_name: tip-database-microservice
    build:
      context: .
      dockerfile: ThreatIntelligencePlatform.DatabaseService/Dockerfile
    ports:
      - "7777:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnectionString=Host=iocs-db;Port=5432;Database=tip_iocs;Username=admin;Password=admin
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    depends_on:
      - iocs-db
      - rabbitmq
    networks:
      - tip-network
  
  collector-microservice:
    container_name: tip-collector-microservice
    build:
      context: .
      dockerfile: ThreatIntelligencePlatform.CollectorService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    depends_on:
      - rabbitmq
    networks:
      - tip-network
  
  normalizer-microservice:
    container_name: tip-normalizer-microservice
    build:
      context: .
      dockerfile: ThreatIntelligencePlatform.NormalizerService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
  
  relevance-checker-microservice:
    container_name: tip-relevance-checker-microservice
    build:
      context: .
      dockerfile: ThreatIntelligencePlatform.RelevanceCheckerService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - tip-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  
  users-db:
    container_name: tip-users-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tip_users
    networks:
      - tip-network
    volumes:
      - users-db-data:/var/lib/postgresql/data
  
  iocs-db:
    container_name: tip-iocs-db
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tip_iocs
    networks:
      - tip-network
    volumes:
      - iocs-db-data:/var/lib/postgresql/data

networks:
  tip-network:
    driver: bridge

volumes:
  users-db-data:
  iocs-db-data:
  rabbitmq-data: