services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: threat-intelligence-platform-frontend/Dockerfile
    ports:
      - "9999:5173"
    networks:
      - tip-network

  main-api:
    container_name: main-api
    build:
      context: .
      dockerfile: ThreatIntelligencePlatform.API/Dockerfile
    ports:
      - "8888:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnectionString=Host=postgres;Port=5432;Database=tip_users;Username=admin;Password=admin
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - ioc-collector
      - normalizer
      - relevance-checker
      - whitelist-collector
    networks:
      - tip-network
  
  ioc-collector:
    container_name: ioc-collector
    build:
      context: .
      dockerfile: ThreatIntelligencePlatform.Worker.IoCCollector/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    depends_on:
      - rabbitmq
      - redis
    networks:
      - tip-network
  
  normalizer:
    container_name: normalizer
    build:
      context: .
      dockerfile: ThreatIntelligencePlatform.Worker.Normalizer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    depends_on:
      - rabbitmq
      - redis
    networks:
      - tip-network
  
  relevance-checker:
    container_name: relevance-checker
    build:
      context: .
      dockerfile: ThreatIntelligencePlatform.Worker.RelevanceChecker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    depends_on:
      - rabbitmq
      - redis
    networks:
      - tip-network
  
  whitelist-collector:
    container_name: whitelist-collector
    build:
      context: .
      dockerfile: ThreatIntelligencePlatform.Worker.WhitelistCollector/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
      - redis
    networks:
      - tip-network
  
  ioc-db:
    container_name: ioc-db
    build:
      context: go-db-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "6060:6060"
    environment:
      BATCH_SIZE: 1000
      TOPIC: ioc.relevant.queue
      BROKER_ADDR: amqp://guest:guest@rabbitmq:5672/
      SERVICE_NAME: golang-db-service
      SERVER_PORT: 8080
      DB_HOST: clickhouse
      DB_PORT: 9000  # Порт по умолчанию для ClickHouse
      DB_USER: user
      DB_PASSWORD: "password"
      DB_NAME: default  # Имя базы данных ClickHouse
    networks:
      - tip-network
    depends_on:
      - rabbitmq
      - clickhouse  # Добавляем зависимость от ClickHouse
      - ioc-collector
      - whitelist-collector
    command: /bin/sh -c "sleep 10 && ./main"
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - tip-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  
  redis:
    container_name: redis
    image: redis:7.2
    environment:
      - REDIS_PASSWORD=redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning --appendonly yes --requirepass redis
    ports:
      - "6379:6379"
    networks:
      - tip-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tip_users
    networks:
      - tip-network
    volumes:
      - users-db-data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "9000:9000"  # Порт для подключения к ClickHouse
      - "8123:8123"  # HTTP-порт ClickHouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: "password"
    networks:
      - tip-network
    volumes:
      - clickhouse-data:/var/lib/clickhouse

networks:
  tip-network:
    driver: bridge

volumes:
  users-db-data:
  rabbitmq-data:
  redis-data:
  clickhouse-data: