// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.2
// source: api/proto/database-v1.proto

package ioc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IoCDto представляет структуру данных для IOCs (Indicators of Compromise)
type IoCDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                                                                       // Идентификатор (может быть пустым)
	Source         string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`                                                                                                                               // Источник
	FirstSeen      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`                                                                                                        // Дата первого обнаружения (может быть пустой)
	LastSeen       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`                                                                                                           // Дата последнего обнаружения (может быть пустой)
	Type           string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`                                                                                                                                   // Тип
	Value          string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`                                                                                                                                 // Значение
	Tags           []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`                                                                                                                                   // Теги
	AdditionalData map[string]string      `protobuf:"bytes,8,rep,name=additional_data,json=additionalData,proto3" json:"additional_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // Дополнительные данные
}

func (x *IoCDto) Reset() {
	*x = IoCDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_database_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IoCDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IoCDto) ProtoMessage() {}

func (x *IoCDto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IoCDto.ProtoReflect.Descriptor instead.
func (*IoCDto) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_proto_rawDescGZIP(), []int{0}
}

func (x *IoCDto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IoCDto) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IoCDto) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *IoCDto) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *IoCDto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IoCDto) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *IoCDto) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *IoCDto) GetAdditionalData() map[string]string {
	if x != nil {
		return x.AdditionalData
	}
	return nil
}

// Запись в бд: Принимает массив и возвращает пока что нчиего
// мб стоит отдельно написать респонс с колвом записанных
type StoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IoCs []*IoCDto `protobuf:"bytes,1,rep,name=IoCs,proto3" json:"IoCs,omitempty"`
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_database_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_proto_rawDescGZIP(), []int{1}
}

func (x *StoreRequest) GetIoCs() []*IoCDto {
	if x != nil {
		return x.IoCs
	}
	return nil
}

type LoadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_database_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_proto_rawDescGZIP(), []int{2}
}

func (x *LoadRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LoadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type LoadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IoCs []*IoCDto `protobuf:"bytes,1,rep,name=IoCs,proto3" json:"IoCs,omitempty"`
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_database_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_proto_rawDescGZIP(), []int{3}
}

func (x *LoadResponse) GetIoCs() []*IoCDto {
	if x != nil {
		return x.IoCs
	}
	return nil
}

// Стримовый запрос для записи IoC
type StreamStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ioc *IoCDto `protobuf:"bytes,1,opt,name=ioc,proto3" json:"ioc,omitempty"` // Один IoC для записи
}

func (x *StreamStoreRequest) Reset() {
	*x = StreamStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_database_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStoreRequest) ProtoMessage() {}

func (x *StreamStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStoreRequest.ProtoReflect.Descriptor instead.
func (*StreamStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_proto_rawDescGZIP(), []int{4}
}

func (x *StreamStoreRequest) GetIoc() *IoCDto {
	if x != nil {
		return x.Ioc
	}
	return nil
}

// Стримовый ответ для загрузки IoC
type StreamLoadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ioc *IoCDto `protobuf:"bytes,1,opt,name=ioc,proto3" json:"ioc,omitempty"` // Один IoC в ответе
}

func (x *StreamLoadResponse) Reset() {
	*x = StreamLoadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_database_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamLoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLoadResponse) ProtoMessage() {}

func (x *StreamLoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLoadResponse.ProtoReflect.Descriptor instead.
func (*StreamLoadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_proto_rawDescGZIP(), []int{5}
}

func (x *StreamLoadResponse) GetIoc() *IoCDto {
	if x != nil {
		return x.Ioc
	}
	return nil
}

var File_api_proto_database_v1_proto protoreflect.FileDescriptor

var file_api_proto_database_v1_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x2d, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x69,
	0x6f, 0x63, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xef, 0x02, 0x0a, 0x06, 0x49, 0x6f, 0x43, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x65,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x53, 0x65, 0x65, 0x6e, 0x12, 0x37,
	0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x6c,
	0x61, 0x73, 0x74, 0x53, 0x65, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x48, 0x0a, 0x0f, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x69, 0x6f, 0x63, 0x2e, 0x49, 0x6f, 0x43, 0x44, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0e, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x1a,
	0x41, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x2f, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x49, 0x6f, 0x43, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x69, 0x6f, 0x63, 0x2e, 0x49, 0x6f, 0x43, 0x44, 0x74, 0x6f, 0x52, 0x04, 0x49,
	0x6f, 0x43, 0x73, 0x22, 0x3b, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x22, 0x2f, 0x0a, 0x0c, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x04, 0x49, 0x6f, 0x43, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x69, 0x6f, 0x63, 0x2e, 0x49, 0x6f, 0x43, 0x44, 0x74, 0x6f, 0x52, 0x04, 0x49, 0x6f, 0x43,
	0x73, 0x22, 0x33, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x03, 0x69, 0x6f, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x69, 0x6f, 0x63, 0x2e, 0x49, 0x6f, 0x43, 0x44, 0x74,
	0x6f, 0x52, 0x03, 0x69, 0x6f, 0x63, 0x22, 0x33, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x03,
	0x69, 0x6f, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x69, 0x6f, 0x63, 0x2e,
	0x49, 0x6f, 0x43, 0x44, 0x74, 0x6f, 0x52, 0x03, 0x69, 0x6f, 0x63, 0x32, 0xe8, 0x01, 0x0a, 0x08,
	0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x12, 0x11, 0x2e, 0x69, 0x6f, 0x63, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2b, 0x0a, 0x04,
	0x4c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x2e, 0x69, 0x6f, 0x63, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x69, 0x6f, 0x63, 0x2e, 0x4c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x17, 0x2e, 0x69, 0x6f, 0x63, 0x2e, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x28, 0x01, 0x12, 0x39, 0x0a, 0x0a, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x2e, 0x69, 0x6f, 0x63, 0x2e,
	0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x69, 0x6f,
	0x63, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x1c, 0x5a, 0x1a, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x67, 0x65, 0x6e, 0x2f, 0x69, 0x6f, 0x63,
	0x3b, 0x69, 0x6f, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_database_v1_proto_rawDescOnce sync.Once
	file_api_proto_database_v1_proto_rawDescData = file_api_proto_database_v1_proto_rawDesc
)

func file_api_proto_database_v1_proto_rawDescGZIP() []byte {
	file_api_proto_database_v1_proto_rawDescOnce.Do(func() {
		file_api_proto_database_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_database_v1_proto_rawDescData)
	})
	return file_api_proto_database_v1_proto_rawDescData
}

var file_api_proto_database_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_database_v1_proto_goTypes = []interface{}{
	(*IoCDto)(nil),                // 0: ioc.IoCDto
	(*StoreRequest)(nil),          // 1: ioc.StoreRequest
	(*LoadRequest)(nil),           // 2: ioc.LoadRequest
	(*LoadResponse)(nil),          // 3: ioc.LoadResponse
	(*StreamStoreRequest)(nil),    // 4: ioc.StreamStoreRequest
	(*StreamLoadResponse)(nil),    // 5: ioc.StreamLoadResponse
	nil,                           // 6: ioc.IoCDto.AdditionalDataEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_api_proto_database_v1_proto_depIdxs = []int32{
	7,  // 0: ioc.IoCDto.first_seen:type_name -> google.protobuf.Timestamp
	7,  // 1: ioc.IoCDto.last_seen:type_name -> google.protobuf.Timestamp
	6,  // 2: ioc.IoCDto.additional_data:type_name -> ioc.IoCDto.AdditionalDataEntry
	0,  // 3: ioc.StoreRequest.IoCs:type_name -> ioc.IoCDto
	0,  // 4: ioc.LoadResponse.IoCs:type_name -> ioc.IoCDto
	0,  // 5: ioc.StreamStoreRequest.ioc:type_name -> ioc.IoCDto
	0,  // 6: ioc.StreamLoadResponse.ioc:type_name -> ioc.IoCDto
	1,  // 7: ioc.Database.Store:input_type -> ioc.StoreRequest
	2,  // 8: ioc.Database.Load:input_type -> ioc.LoadRequest
	4,  // 9: ioc.Database.StreamStore:input_type -> ioc.StreamStoreRequest
	2,  // 10: ioc.Database.StreamLoad:input_type -> ioc.LoadRequest
	8,  // 11: ioc.Database.Store:output_type -> google.protobuf.Empty
	3,  // 12: ioc.Database.Load:output_type -> ioc.LoadResponse
	8,  // 13: ioc.Database.StreamStore:output_type -> google.protobuf.Empty
	5,  // 14: ioc.Database.StreamLoad:output_type -> ioc.StreamLoadResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_database_v1_proto_init() }
func file_api_proto_database_v1_proto_init() {
	if File_api_proto_database_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_database_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IoCDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_database_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_database_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_database_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_database_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_database_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamLoadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_database_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_database_v1_proto_goTypes,
		DependencyIndexes: file_api_proto_database_v1_proto_depIdxs,
		MessageInfos:      file_api_proto_database_v1_proto_msgTypes,
	}.Build()
	File_api_proto_database_v1_proto = out.File
	file_api_proto_database_v1_proto_rawDesc = nil
	file_api_proto_database_v1_proto_goTypes = nil
	file_api_proto_database_v1_proto_depIdxs = nil
}
